/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banksimulator.view;

import banksimulator.Simulation;
import banksimulator.SimulationConfig;
import banksimulator.SimulationListener;
import banksimulator.SimulatorAgent;
import banksimulator.model.Account;
import banksimulator.model.Log;
import banksimulator.view.windowsinterfaces.SimulationSettingsDialogInterface;
import java.util.ArrayList;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.locks.ReentrantLock;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author scavenger
 */
public class MainWindow extends javax.swing.JFrame 
        implements SimulationSettingsDialogInterface, 
        GeneralLogAreaWriterInterface, SimulationListener {
    
    private Simulation m_simulation = null;
    
    private SimulationConfig m_currentConfig = new SimulationConfig();
    private static final String THREADS = "Threads: ";
    private static final String AGENTS = "Agentes: ";
    private static final String OPERATIONS = "Operações: ";
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        m_buttonPause.setEnabled(false);
        m_buttonStop.setEnabled(false);
        
        DefaultCaret caret = (DefaultCaret) m_generalLogArea.getCaret();
        caret.setUpdatePolicy( DefaultCaret.ALWAYS_UPDATE );
        
        DefaultCaret caret2 = (DefaultCaret) m_agentArea01.getCaret();
        caret2.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        
        DefaultCaret caret3 = (DefaultCaret) m_agentArea02.getCaret();
        caret3.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        
    }

    private void settingListeners(){
        SimulatorAgent[] agents = m_simulation.getAgents();
        for(int i=0; i < agents.length; i++)
            agents[i].setListener(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_agentCombo01 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_agentArea01 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        m_agentArea02 = new javax.swing.JTextArea();
        m_agentCombo02 = new javax.swing.JComboBox<>();
        m_buttonStart = new javax.swing.JButton();
        m_buttonSettings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        m_GeneralLogScroolPane = new javax.swing.JScrollPane();
        m_generalLogArea = new javax.swing.JTextArea();
        m_labelThreads = new javax.swing.JLabel();
        m_labelAgents = new javax.swing.JLabel();
        m_labelOperationNumber = new javax.swing.JLabel();
        m_buttonPause = new javax.swing.JButton();
        m_buttonStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Simulator");

        m_agentCombo01.setEnabled(false);
        m_agentCombo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_agentCombo01ActionPerformed(evt);
            }
        });

        m_agentArea01.setEditable(false);
        m_agentArea01.setColumns(20);
        m_agentArea01.setRows(5);
        jScrollPane1.setViewportView(m_agentArea01);

        m_agentArea02.setEditable(false);
        m_agentArea02.setColumns(20);
        m_agentArea02.setRows(5);
        jScrollPane2.setViewportView(m_agentArea02);

        m_agentCombo02.setEnabled(false);
        m_agentCombo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_agentCombo02ActionPerformed(evt);
            }
        });

        m_buttonStart.setText("Iniciar");
        m_buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_buttonStartActionPerformed(evt);
            }
        });

        m_buttonSettings.setText("Configurar");
        m_buttonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_buttonSettingsActionPerformed(evt);
            }
        });

        jLabel1.setText("Agentes Logs");

        m_generalLogArea.setEditable(false);
        m_generalLogArea.setColumns(20);
        m_generalLogArea.setRows(5);
        m_generalLogArea.setFocusable(false);
        m_generalLogArea.setRequestFocusEnabled(false);
        m_GeneralLogScroolPane.setViewportView(m_generalLogArea);

        m_labelThreads.setText("Threads: ");

        m_labelAgents.setText("Agentes:");

        m_labelOperationNumber.setText("Total Operações:");

        m_buttonPause.setText("Pausar");
        m_buttonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_buttonPauseActionPerformed(evt);
            }
        });

        m_buttonStop.setText("Abortar");
        m_buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_buttonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_GeneralLogScroolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(m_agentCombo02, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(m_agentCombo01, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)))
                                    .addComponent(jScrollPane2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_labelThreads)
                            .addComponent(m_labelAgents)
                            .addComponent(m_labelOperationNumber))
                        .addGap(100, 100, 100)
                        .addComponent(m_buttonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_buttonPause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_buttonStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_buttonSettings)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {m_buttonPause, m_buttonSettings, m_buttonStart, m_buttonStop});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {m_agentCombo01, m_agentCombo02});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_labelThreads)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_labelAgents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_labelOperationNumber))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m_buttonSettings)
                        .addComponent(m_buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m_buttonPause)
                        .addComponent(m_buttonStop)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_agentCombo01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(m_agentCombo02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m_GeneralLogScroolPane))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {m_buttonPause, m_buttonSettings, m_buttonStart, m_buttonStop});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {m_agentCombo01, m_agentCombo02});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_buttonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_buttonSettingsActionPerformed
        SimulationSettingsDialog dialog = new SimulationSettingsDialog(this, true, m_currentConfig);
        dialog.setListener(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_m_buttonSettingsActionPerformed

    private void m_buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_buttonStartActionPerformed

        m_agentArea01.setText("");
        m_agentArea02.setText("");
        
        disableComboBoxes();
        clearGeneralLogArea();
        startSimulation();
        
        settingCombosBoxes();
        updateLabels();
        enableComboBoxes();
        m_buttonStart.setEnabled(false);
        m_buttonPause.setEnabled(true);
        m_buttonStop.setEnabled(true);
        m_buttonSettings.setEnabled(false);
    }//GEN-LAST:event_m_buttonStartActionPerformed
    
    private void startSimulation(){
        m_simulation = new Simulation(m_currentConfig,this);
        settingListeners();
        m_simulation.start();
        System.out.println("SIMULACAO INICIADA!");
    }
    
    private void clearGeneralLogArea(){
        m_generalLogArea.selectAll();
        m_generalLogArea.replaceSelection("");
        m_generalLogArea.setCaretPosition(0);
    }
    
    private void clearAgentArea01(){
        m_agentArea01.selectAll();
        m_agentArea01.replaceSelection("");
        m_agentArea01.setCaretPosition(0);
    }
    
    private void m_agentCombo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_agentCombo02ActionPerformed
        int selectedIndex = m_agentCombo02.getSelectedIndex();
          if (selectedIndex <= 0)
           return;
       
       Account account =  m_simulation.getAgentAt(selectedIndex-1).getSimulatorClient().getAccount();
       CopyOnWriteArrayList<Log> logs = account.getLogList();
       String text="";
       
       for(Log l: logs){
           text+= l.getReport();
       }
       text+= "\nTOTAL REGISTROS: " + logs.size();
       m_agentArea02.setText("");
       m_agentArea02.setText(text);
    }//GEN-LAST:event_m_agentCombo02ActionPerformed

    private void m_agentCombo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_agentCombo01ActionPerformed
       int selectedIndex = m_agentCombo01.getSelectedIndex();
       if (selectedIndex <= 0 ){
           return;
       }
       
       clearAgentArea01();
       Account account =  m_simulation.getAgentAt(selectedIndex-1).getSimulatorClient().getAccount();
       CopyOnWriteArrayList<Log> logs = account.getLogList();
       
       String text="";
       
       for(Log l: logs){
           text+= l.getReport();
       }
       
       text+= "\nTOTAL REGISTROS: " + logs.size();
       m_agentArea01.setText(text);
    }//GEN-LAST:event_m_agentCombo01ActionPerformed

    private void m_buttonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_buttonPauseActionPerformed
        pauseOrResumeSimulation();
    }//GEN-LAST:event_m_buttonPauseActionPerformed

    private void pauseOrResumeSimulation(){
        boolean status = m_simulation.isPaused();
        if (!status){
            m_simulation.pause();
            m_buttonPause.setText("Resume");
        } else {
            m_simulation.resume();
            m_buttonPause.setText("Pause");
        }
    }
    
    private void m_buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_buttonStopActionPerformed
        m_simulation.interrupt();
    }//GEN-LAST:event_m_buttonStopActionPerformed

    private void enableComboBoxes(){
        m_agentCombo01.setEnabled(true);
        m_agentCombo02.setEnabled(true);
    }
    
    private void disableComboBoxes(){
        m_agentCombo01.setEnabled(false);
        m_agentCombo02.setEnabled(false);
    }
    
    private void settingCombosBoxes(){
        m_agentCombo01.setSelectedIndex(-1);
        m_agentCombo02.setSelectedIndex(-1);
        
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) m_agentCombo01.getModel();
        DefaultComboBoxModel<String> model2 = (DefaultComboBoxModel<String>) m_agentCombo02.getModel();
        
        model.removeAllElements();
        model2.removeAllElements();
        
        model.addElement("EXTRATO de um agente");
        model2.addElement("EXTRATO de um agente");
        
        SimulatorAgent[] agents = m_simulation.getAgents();
        for(int i=0; i < agents.length; i++){
            model.addElement( agents[i].getName());
            model2.addElement(agents[i].getName());
        }
        //model.setSelectedItem(null);
        //model2.setSelectedItem(null);
        m_agentCombo01.setModel(model);
        m_agentCombo01.setSelectedIndex(0);
        
        //m_agentCombo02.setModel(model2);
        m_agentCombo02.setSelectedIndex(0);
        
       
        //m_agentCombo01.updateUI();
    }
    
    private void updateLabels(){
        m_labelThreads.setText(THREADS + m_simulation.getSettings().m_poolSize);
        m_labelOperationNumber.setText(OPERATIONS + 
                m_simulation.getSettings().m_agentConfig.m_operationsNumber);
        m_labelAgents.setText( AGENTS + m_simulation.getSettings().m_agentSize);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane m_GeneralLogScroolPane;
    private javax.swing.JTextArea m_agentArea01;
    private javax.swing.JTextArea m_agentArea02;
    private javax.swing.JComboBox<String> m_agentCombo01;
    private javax.swing.JComboBox<String> m_agentCombo02;
    private javax.swing.JButton m_buttonPause;
    private javax.swing.JButton m_buttonSettings;
    private javax.swing.JButton m_buttonStart;
    private javax.swing.JButton m_buttonStop;
    private javax.swing.JTextArea m_generalLogArea;
    private javax.swing.JLabel m_labelAgents;
    private javax.swing.JLabel m_labelOperationNumber;
    private javax.swing.JLabel m_labelThreads;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onConfirm(SimulationConfig settings) {
        /*callback da SimulationSettingsDialog*/
        m_currentConfig = settings;
    }

    @Override
    public void onCancel(SimulationConfig settings) {
        /*callback da SimulationSettingsDialog*/
         m_currentConfig = settings;
    }

    @Override
    public void writeOnLogArea(String write) {
        m_generalLogArea.append(write);
    }

    @Override
    public void simulationStart() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void simulationPaused() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void simulationResumed() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void simulationInterrupted() {
        m_buttonStop.setEnabled(false);
        System.out.println("SIMULATION INTERRUPTED ");
    }
    
    @Override
    public void simulationEnd() {
        m_buttonStart.setEnabled(true);
        m_buttonPause.setEnabled(false);
        m_buttonStop.setEnabled(false);
        m_buttonSettings.setEnabled(true);
    }
    
}
